name: GitHub Actions Build

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Auto Increment Version
      uses: MCKanpolat/auto-semver-action@v2
      id: versioning
      with:
        releaseType: minor 
        incrementPerCommit: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure build
      run: ./premake5 vs2022

    - name: Build
      run: |
        msbuild -m build/Universal-Snowdrop-Modloader.sln /property:Configuration=Release /property:Platform=x64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Universal-Snowdrop-Modloader
        path: dist/dll/*

    - name: Upload Release (Main)
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'patrickmollohan/Universal-Snowdrop-Modloader'
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: false
        name: Universal Snowdrop Modloader v${{ steps.versioning.outputs.version }}
        bodyFile: "release.md"
        tag: v${{ steps.versioning.outputs.version }}
        artifacts: bin/Universal-Snowdrop-Modloader.zip

    - name: Get release info
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'patrickmollohan/Universal-Snowdrop-Modloader'
      id: release_info_x64
      uses: cardinalby/git-get-release-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: x64-latest

    - name: Upload Release
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'patrickmollohan/Universal-Snowdrop-Modloader'
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ steps.release_info_x64.outputs.name }}
        body: ${{ steps.release_info_x64.outputs.body }}
        tag: ${{ steps.release_info_x64.outputs.tag_name }}
        artifacts: dist/zip/*.zip
