name: GitHub Actions Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release (e.g., v1.0.0)'
        required: false
        default: ''
      create_release:
        description: 'Set to "true" to create a GitHub release'
        required: false
        default: 'false'

  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Configure build
      run: ./premake5 vs2022

    - name: Build
      run: |
        msbuild -m build/Universal-Snowdrop-Modloader.sln /property:Configuration=Release /property:Platform=x64

    - name: Prepare files for packaging
      run: |
        mkdir dist
        copy bin/Release/version.dll dist/
        copy version.ini dist/

    - name: Zip the files
      run: |
        pwsh -Command "Compress-Archive -Path dist/version.dll,dist/version.ini -DestinationPath dist/Universal-Snowdrop-Modloader.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Universal-Snowdrop-Modloader
        path: dist/Universal-Snowdrop-Modloader.zip

  create_release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_release == 'true' && github.event.inputs.version != '' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Upload Release to GitHub
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: false
        name: Universal Snowdrop Modloader ${{ github.event.inputs.version }}
        bodyFile: "release.md"
        tag: ${{ github.event.inputs.version }}
        artifacts: dist/Universal-Snowdrop-Modloader.zip
